services:
  api:
    build:
      context: .                 
      dockerfile: apps/api/Dockerfile
    container_name: api
    env_file:
      - .env.dev
    environment:
      - ENV_FILE=.env.dev      
    command: pnpm dev 
    volumes:
      - ./data:/app/data:ro
      - ./apps/api:/app/apps/api
      - ./packages/shared:/app/packages/shared    
    ports:
      - "4000:4000"
    depends_on:
      - mailhog
    healthcheck:
      test:
        [
          "CMD",
          "node",
          "-e",
          "require('http').get('http://localhost:4000/api/v1/health', r => process.exit(r.statusCode===200 ? 0 : 1)).on('error', () => process.exit(1))"
        ]
      interval: 30s
      timeout: 2s
      retries: 5
      start_period: 10s    
    restart: unless-stopped  

  web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile 
    container_name: web
    command: pnpm dev --host 0.0.0.0
    ports:
      - "5173:5173"
    depends_on:
      api: 
        condition: service_healthy 
    volumes: 
      - ./apps/web:/app/apps/web
      - ./packages/shared:/app/packages/shared 
    restart: unless-stopped

  mailhog:
    image: mailhog/mailhog:v1.0.1
    container_name: mailhog
    ports:
      - "8025:8025" # UI at http://localhost:8025
      - "1025:1025" # SMTP
    restart: unless-stopped
